---
name: vet
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
 vet:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
        cache-dependency-path: "**/*.sum"

    - name: Install tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest && \
        go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: vet
      run: go run ./.github/workflows/vet.go